name: build-site-imd
run-name: build live site imd

on:
  push:
    branches: ["main"]
    
  workflow_dispatch:
  
jobs:

  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout branch contents
        uses: actions/checkout@v3

      - name: Build web site
        run: bundle exec jekyll build
        
      - name: Clear publish folder
        run: rm -rf $HOME/public_html/dalmolingroup.imd.ufrn.br
        
      - name: Publish
        run: cp -r _site $HOME/public_html/dalmolingroup.imd.ufrn.br
