name: build-site-imd
run-name: build live site imd

on:
  push:
    branches: ["main"]
    
  workflow_dispatch:
  
env:
  PREVIEWS_FOLDER: preview

permissions:
  contents: write

jobs:
  build-site:
    runs-on: self-hosted

    steps:
      - name: Print contexts
        uses: crazy-max/ghaction-dump-context@v1

      - name: Checkout branch contents
        uses: actions/checkout@v3

      - name: Get Pages url
        id: pages
        uses: actions/configure-pages@v2
        with:
          enablement: false

      - name: Build live version of site
        run: bundle exec jekyll build
