name: build-site-imd
run-name: build live site imd

on:
  push:
    branches: ["main"]
    
  workflow_dispatch:
  
env:
  PREVIEWS_FOLDER: preview

permissions:
  contents: write

jobs:
  build-site:
    runs-on: self-hosted

    steps:
      - name: Checkout branch contents
        uses: actions/checkout@v3

      - name: install bundle gems
        run: ~/install_gems.sh
        
      - name: build web site
        run: ~/build_site.sh
