name: build-site-imd
run-name: build live site imd

on:
  push:
    branches: ["main"]
    
  workflow_dispatch:
  
jobs:

  deployment:
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout branch contents
        uses: actions/checkout@v3

      - name: Build web site
        run: bundle exec jekyll build
        
      - name: Clean up publish folder before publishing
        run: rm -rf $HOME/websites/dalmolingroup.imd.ufrn.br
        
      - name: Publish website
        run: cp -r _site $HOME/websites/dalmolingroup.imd.ufrn.br
      
      - name: Clean up workspace
        run: rm -rf ${{ github.workspace }}/*
